### ISSUE TITLE
trader.say and cpu usage issue in 1.41.00

### ISSUE THREAD

**Issue by Apzeltukas** [JulyIghor/QtBitcoinTrader#282]
hello, 
windows 10
since 1.41.00 64bit update i have 2 issues:
trader.say() does not speak any more. (windows speech ability works, not sure if they have ties). it had windows speech related error before, i believe, now just silent.
window on hitbtc platform has cpu usage issues. it is often (not responding) for a few minutes. once a script opened 3 identical orders instead of 1 it was programed to, for some reason.
how can i help more?

**Comment by JulyIghor** [comment]
Can you please confirm, is 2 and 3 fixed in latest release?

**Comment by Apzeltukas** [comment]
I will try out and report back.

In the meantime, it got tagged by Avast at first about update and later trader itself
![1](https://user-images.githubusercontent.com/35662434/195693122-89222d37-0e2b-4d9e-a5de-ca4d6d95be63.JPG)
![2](https://user-images.githubusercontent.com/35662434/195693153-5f64bdec-da99-4136-bd65-a1ede075a7fa.JPG)

**Comment by JulyIghor** [comment]
> In the meantime, it got tagged by Avast at first about update and later trader itself

Thanks, I'll report the false detection to Avast

**Comment by Apzeltukas** [comment]
number 2 not fixed. additional info. if program is left on screen, after 24h program is not responding due to large memory/cpu usage. but if program is hidden to tray, after 24h memory and cpu usage is not affected. will test some other exchanges next for the same issue.

number 3 not fixed. still the same. loads, but not updates.

**Comment by Apzeltukas** [comment]
Number 2 is the same for Poloniex and Binance exchanges. Memory use increase if trader is left open on screen. Memory does not increase if trader is hidden to tray.

**Comment by JulyIghor** [comment]
> Number 2 is the same for Poloniex and Binance exchanges. Memory use increase if trader is left open on screen. Memory does not increase if trader is hidden to tray.

It is possible that you have a loop in your script code, we can't inspect it without the code itself.
But for sure you may try to inspect it by yourself, and add to the log output your trade attempts.
Most likely you will see a infinite open order commands that may cause the memory issue.

**Comment by Apzeltukas** [comment]
> It is possible that you have a loop in your script code, we can't inspect it without the code itself. But for sure you may try to inspect it by yourself, and add to the log output your trade attempts. Most likely you will see a infinite open order commands that may cause the memory issue.

No. Without any scripts running, just sitting open fullscreen for like 4 days, Poloniex grew to 1900mb of memory. 
While other instances hidden in the tray with scripts running did not increased their memory use.
Can I help in any way?

**Comment by JulyIghor** [comment]
> No. Without any scripts running, just sitting open fullscreen for like 4 days, Poloniex grew to 1900mb of memory.

Maybe you had opened a Debug window?

**Comment by Apzeltukas** [comment]
> Maybe you had opened a Debug window?

No. Do not use a debug window, it is always closed. Unless it is somehow active while closed since Enabled is selected when i open it. 
So far i use trader minimized to tray. No significant memory growth for weeks while in tray. That is the only difference i can tell.

**Comment by JulyIghor** [comment]
> No. Do not use a debug window, it is always closed. Unless it is somehow active while closed since Enabled is selected when i open it. So far i use trader minimized to tray. No significant memory growth for weeks while in tray. That is the only difference i can tell.

Thanks, we have reproduced it, but not found a reason for that yet. We will keep trying to solve it.
